# -*- coding: utf-8 -*-
"""valormas_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12AejB74LxZZKcfJ-t-knDG2hKfHvJIK7
"""

def extraerListaPalabras(t, n):
    palabras = t.split()    #### se obtine la lista de palabras hacindo uso de la función split().
    lista = sorted([palabra for palabra in palabras if len(palabra) >= n and palabra.islower()]) #### se asigna a la variable lista un array ordenado el cual contine los items que cumplen con las condicionres establecidas.
    return lista ## se retorna la varible de tipo array.



texto = input("Por favor, ingresa una cadena de texto: ")  ### Entrada: "El desarrollo de software es una habilidad fundamental para los ingenieros informáticos".
numeroCaracteres = float(input("Por favor, ingresa numero de caracteres a seleccionar: ")) ### Debe ser un Numero.

print(extraerListaPalabras(texto, numeroCaracteres)) ### llamamos la función, pasamos los parametro ingresados e impprimimos por pantalla.